### ISSUE TITLE
Prune/Fix Dead Links (2023)

### ISSUE THREAD

**Issue by bytecauldron** [bytecauldron/awesome-gamemaker#7]
I noticed a couple of links are leading to 404's right now, so I'll click on each one and see if content moved/disappeared.

**Comment by bytecauldron** [comment]
The following links appear to 404, deprecated/unmaintained, or needs a link changed. (Still working on this)

### Utilities

- [ ] https://rousr.itch.io/outsidethebox (Not sure if babyjeans's is still maintaining these anymore?)
- [ ] https://github.com/Lojemiru/Stopwatch (Looks like Lojemiru is moving away from GM, so this is currently unmaintained. Not sure if I should remove it yet or not.)
- [ ] https://github.com/daikon-games/gm-cadence (Deprecated due to the introduction of GameMaker 2022.5 Time Sources. Speaking of, if you run into any additional libraries deprecated due to new native GM features, please let me know!)
- [ ] "Mathematical Scripts" needs to be updated to the GitHub repo instead of the Itch page. https://github.com/adam-rumpf/game-maker-scripts
- [ ] https://github.com/katsaii/gml-prelude Has been archived. Probably needs to be removed since it's not maintained?

### Physics

- [ ] https://github.com/Lojemiru/Loj-Hadron-Collider Deprecated. I'm very sad about this since there is slim-pickings for open-source physics libraries. I might keep this on this list until I confirm it doesn't work with the latest LTS?

### Audio

Audio has gone through some native improvements over 2022. Not sure how many of these should be removed yet, if at all. For example, I can't imagine SoLoud has any support for the latest LTS.

### Levels

- [ ] https://github.com/kirillzhosul/world-generation Archived, likely not maintained.

### Lighting

- [ ] 3D Fragment Point Lights should probably be moved to the 3D section.

**Comment by Totobal5** [comment]
https://github.com/Lojemiru/Loj-Hadron-Collider 
Still work on LTS and Stable!

**Comment by bytecauldron** [comment]
Thanks for checking! I'll leave Loj's work on there when/if things start breaking down. Much appreciated.

**Comment by bytecauldron** [comment]
Babyjeans informed me the rousr 2.3 libraries are no longer maintained, but I will be putting the link to the archived projects (Dissonance/OutsideTheBox) in the `Useful Extras` section. https://gitlab.com/rousr-release/

**Comment by bytecauldron** [comment]
Links have been fixed/pruned! https://github.com/bytecauldron/awesome-gamemaker/commit/8b7c594f4caea8ec6cdc01fab560f3486dc3948a https://github.com/bytecauldron/awesome-gamemaker/commit/43313dbac8d2135bed0c2e7103b0809eb532d9f6
